### ISSUE TITLE
Can llm-api be used to run a model with GPU rather than CPU

### ISSUE THREAD

**Issue by niparis** [1b5d/llm-api#4] opened 2023-04-18 18:10 UTC
The code seem to only support CPU at the moment. 

Would docker be able to access GPUs ?

**Comment by 1b5d** [comment] 2023-04-22 19:35
I'm currently trying to work out a docker image that can run GPTQ for Llama, let me know if you have some tips

**Comment by 1b5d** [comment] 2023-04-23 19:54
@niparis I just pushed an image to run on GPU using GPTQ-for-llama, please test it out and let me know your thoughts! here is the [image](https://hub.docker.com/layers/1b5d/llm-api/0.0.1-gptq-llama-cuda/images/sha256-3dc1ed97b5c9e40c90210e8f7e802a8aaaf5d1ff686dd4c6316c9b69c076a47f?context=explore)

I also added a section for more details in the [README.md](https://github.com/1b5d/llm-api/blob/main/README.md#llama--alpaca-on-gpu---using-gptq-for-llama-beta)

**Comment by cmhamiche** [comment] 2023-05-06 20:30
It is working great.
One suggestion tho, can we get to adjust max_length and max_new_tokens as parameters please ? Default values are at 50 for both.
I edited gptq_llama.py in the meantime:
l154: max_length = params.get("max_length", 2048)
l157: max_new_tokens = params.get("max_new_tokens", 2048)
l168: max_new_tokens=max_new_tokens,

edit: I tried this before but it did not work, that's why I'm bothering you.

>>> llm = LLMAPI(
...     host_name="http://localhost:8000",
...     params={"max_length": 2048, "max_new_tokens": 2048, "temp": 0.2},
...     verbose=True
... )

**Comment by cmhamiche** [comment] 2023-05-07 10:02
Sorry, I'm actually dumb I just had to edit the config.yaml. 

edit: Well, I was talking too fast
`Input length of input_ids is 240, but `max_length` is set to 50. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.`
I'll put the values in my script like this 
```
llm = LLMAPI(
    host_name="http://localhost:8000",
    params = {"n_predict": 300, "temp": 0.2, "max_length": 2048, "max_new_tokens": 2048},
    verbose=True
)
```

Also it'd be great if the models were stored in separate folders instead of gptq_llama so tokenizer.model config.json and tokenizer_config.json don't get overwritten each time we change modelss. 

Now on the bright side, this implementation is way better than using the textgen webui's api, it's simpler and faster. I'm using a french finetuned model and use a script that'll output on tty, Since I barely know what I'm doing, that saves me the headache of having to deal with unicode, utf8 and special characters for the time being.

**Comment by 1b5d** [comment] 2023-06-08 17:35
Thanks for the feedback and for being patient, I usually have very little time to work on this project. But I will adjust the directory thing for sure!

**Comment by 1b5d** [comment] 2023-06-09 15:38
I have pushed a new image with the requested fix, you can find it in the latest README.me file

**Comment by 1b5d** [comment] 2023-11-12 23:31
Closing this for being outdated after supporting different GPU options

**Closed as completed by 1b5d** 2023-11-12 23:31 UTC
